# Python: jour 2

In [12]:
import pandas as pd
import re
from datetime import datetime, date, time

## Encodages:
- ASCII
- latin 1: ISO-8859-1
- ISO-8859-15
- Windows 1252 (alias CP1252, ANSI)
- Unicode : UTF-8, UTF-16, UTF-32, ..

In [1]:
texte = "Le cœur  de la ville L'Haÿ-les-Roses n'a pas de prix en €"
print(texte)

Le cœur  de la ville L'Haÿ-les-Roses n'a pas de prix en €

In [2]:
texte.encode('UTF-8')

b"Le c\xc5\x93ur  de la ville L'Ha\xc3\xbf-les-Roses n'a pas de prix en \xe2\x82\xac"

In [3]:
texte.encode('cp1252')

b"Le c\x9cur  de la ville L'Ha\xff-les-Roses n'a pas de prix en \x80"

In [4]:
texte.encode('ISO-8859-15')

b"Le c\xbdur  de la ville L'Ha\xff-les-Roses n'a pas de prix en \xa4"

In [6]:
# UnicodeEncodeError: 'latin-1' codec can't encode character '\u0153' in position 4: ordinal not in range(256)
# texte.encode('ISO-8859-1')

In [8]:
code = b"\xe2\x82\xac"
print(code.decode('UTF-8'))
print(code.decode('cp1252'))

€
â‚¬

## Communes de France

In [21]:
dtype = {
    'code_insee': str,
    'code_postal': str,
    'reg_code': str,
    'dep_code': str
}
df_villes = pd.read_csv('data/villes_fr.csv', encoding='cp1252', sep=';', dtype=dtype)
df_villes.head()

,code_insee,code_postal,nom_standard,nom_sans_pronom,dep_code,dep_nom,reg_code,reg_nom,population,superficie_hectare,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre
0,01001,01400,L'Abergement-Clémenciat,Abergement-Clémenciat,01,Ain,84,Auvergne-Rhône-Alpes,832,1565,53.0,242,206,272,"46,151","4,921","46,153","4,926"
1,01002,01640,L'Abergement-de-Varey,Abergement-de-Varey,01,Ain,84,Auvergne-Rhône-Alpes,267,912,29.0,483,290,748,"46,007","5,423","46,009","5,428"
2,01004,01500,Ambérieu-en-Bugey,Ambérieu-en-Bugey,01,Ain,84,Auvergne-Rhône-Alpes,14854,2448,607.0,379,237,753,"45,958","5,36","45,961","5,373"
3,01005,01330,Ambérieux-en-Dombes,Ambérieux-en-Dombes,01,Ain,84,Auvergne-Rhône-Alpes,1897,1605,118.0,290,265,302,"45,996","4,903","45,996","4,912"
4,01006,01300,Ambléon,Ambléon,01,Ain,84,Auvergne-Rhône-Alpes,113,602,19.0,589,330,940,"45,748","5,601","45,75","5,594"

In [22]:
type(df_villes)

pandas.DataFrame

In [25]:
df_villes.info()

<class 'pandas.DataFrame'>
RangeIndex: 34935 entries, 0 to 34934
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   code_insee          34935 non-null  str
 1   code_postal         34932 non-null  str
 2   nom_standard        34935 non-null  str
 3   nom_sans_pronom     34935 non-null  str
 4   dep_code            34935 non-null  str
 5   dep_nom             34935 non-null  str
 6   reg_code            34935 non-null  str
 7   reg_nom             34935 non-null  str
 8   population          34935 non-null  int64
 9   superficie_hectare  34935 non-null  int64
 10  densite             34932 non-null  float64
 11  altitude_moyenne    34935 non-null  int64
 12  altitude_minimale   34935 non-null  int64
 13  altitude_maximale   34935 non-null  int64
 14  latitude_mairie     34935 non-null  str
 15  longitude_mairie    34935 non-null  str
 16  latitude_centre     34926 non-null  str
 17  longitude_centre    34926 non-null  str
dtypes: float64(1), int64(5), str(12)
memory usage: 4.8 MB

In [26]:
df_villes.describe()

,population,superficie_hectare,densite,altitude_moyenne,altitude_minimale,altitude_maximale
count,3.493500e+04,3.493500e+04,34932.000000,34935.000000,34935.000000,34935.000000
mean,1.936405e+03,1.763584e+03,169.279056,279.172606,188.710405,384.897782
std,1.498968e+04,1.481510e+04,752.070774,288.589425,201.561722,452.958268
min,0.000000e+00,2.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,1.970000e+02,6.490000e+02,18.000000,105.000000,55.000000,132.000000
50%,4.570000e+02,1.088000e+03,41.000000,189.000000,134.000000,231.000000
75%,1.164000e+03,1.867000e+03,100.000000,337.000000,252.000000,436.500000
max,2.133111e+06,1.871833e+06,28220.000000,2713.000000,9589.000000,4808.000000

In [ ]:
# Series : column (or row)
df_villes['nom_standard']

0        L'Abergement-Clémenciat
1          L'Abergement-de-Varey
2              Ambérieu-en-Bugey
3            Ambérieux-en-Dombes
4                        Ambléon
                  ...
34930              M'Tsangamouji
34931                   Ouangani
34932                   Pamandzi
34933                       Sada
34934                   Tsingoni
Name: nom_standard, Length: 34935, dtype: str

In [28]:
df_villes.nom_standard

0        L'Abergement-Clémenciat
1          L'Abergement-de-Varey
2              Ambérieu-en-Bugey
3            Ambérieux-en-Dombes
4                        Ambléon
                  ...
34930              M'Tsangamouji
34931                   Ouangani
34932                   Pamandzi
34933                       Sada
34934                   Tsingoni
Name: nom_standard, Length: 34935, dtype: str

In [30]:
# liste de colonnes
df_villes[['nom_standard', 'code_postal']]

                  nom_standard code_postal
0      L'Abergement-Clémenciat       01400
1        L'Abergement-de-Varey       01640
2            Ambérieu-en-Bugey       01500
3          Ambérieux-en-Dombes       01330
4                      Ambléon       01300
...                        ...         ...
34930            M'Tsangamouji       97650
34931                 Ouangani       97670
34932                 Pamandzi       97615
34933                     Sada       97640
34934                 Tsingoni       97680

[34935 rows x 2 columns]

In [31]:
df_villes.iloc[:3, :4]

  code_insee code_postal             nom_standard        nom_sans_pronom
0      01001       01400  L'Abergement-Clémenciat  Abergement-Clémenciat
1      01002       01640    L'Abergement-de-Varey    Abergement-de-Varey
2      01004       01500        Ambérieu-en-Bugey      Ambérieu-en-Bugey

In [ ]:
# derniere ligne : Series
df_villes.iloc[-1]

code_insee               97617
code_postal              97680
nom_standard          Tsingoni
nom_sans_pronom       Tsingoni
dep_code                   976
dep_nom                Mayotte
reg_code                     6
reg_nom                Mayotte
population               13934
superficie_hectare        3426
densite                  407.0
altitude_moyenne           147
altitude_minimale            0
altitude_maximale          480
latitude_mairie         -12,79
longitude_mairie        45,105
latitude_centre        -12,782
longitude_centre        45,134
Name: 34934, dtype: object

In [33]:
df_villes.iloc[20_000:20_005]

,code_insee,code_postal,nom_standard,nom_sans_pronom,dep_code,dep_nom,reg_code,reg_nom,population,superficie_hectare,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre
20000,55001,55130,Abainville,Abainville,55,Meuse,44,Grand Est,285,1360,21.0,323,282,388,"48,53","5,494","48,533","5,515"
20001,55002,55400,Abaucourt-Hautecourt,Abaucourt-Hautecourt,55,Meuse,44,Grand Est,99,970,10.0,224,210,251,"49,197","5,54","49,197","5,549"
20002,55004,55110,Aincreville,Aincreville,55,Meuse,44,Grand Est,81,910,9.0,235,187,314,"49,368","5,121","49,37","5,116"
20003,55005,55130,Amanty,Amanty,55,Meuse,44,Grand Est,35,1118,3.0,389,295,426,"48,518","5,613","48,515","5,604"
20004,55007,55300,Ambly-sur-Meuse,Ambly-sur-Meuse,55,Meuse,44,Grand Est,237,638,37.0,232,204,273,"49,019","5,443","49,023","5,452"

In [34]:
df_villes.iloc[-1:]

,code_insee,code_postal,nom_standard,nom_sans_pronom,dep_code,dep_nom,reg_code,reg_nom,population,superficie_hectare,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre
34934,97617,97680,Tsingoni,Tsingoni,976,Mayotte,6,Mayotte,13934,3426,407.0,147,0,480,"-12,79","45,105","-12,782","45,134"

In [35]:
df_villes.loc[df_villes.population >= 500_000]

,code_insee,code_postal,nom_standard,nom_sans_pronom,dep_code,dep_nom,reg_code,reg_nom,population,superficie_hectare,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre
4342,13055,13000,Marseille,Marseille,13,Bouches-du-Rhône,93,Provence-Alpes-Côte d'Azur,873076,24060,3629.0,20,0,652,"43,296","5,37",NaN,NaN
11793,31555,31100,Toulouse,Toulouse,31,Haute-Garonne,76,Occitanie,504078,11809,4269.0,148,115,263,"43,605","1,444","43,596","1,432"
27082,69123,69000,Lyon,Lyon,69,Rhône,84,Auvergne-Rhône-Alpes,522250,4790,10903.0,237,162,305,"45,764","4,836",NaN,NaN
29244,75056,75000,Paris,Paris,75,Paris,11,Île-de-France,2133111,10540,20238.0,35,28,131,"48,857","2,352",NaN,NaN

In [36]:
df_villes.population >= 500_000

0        False
1        False
2        False
3        False
4        False
         ...
34930    False
34931    False
34932    False
34933    False
34934    False
Name: population, Length: 34935, dtype: bool

In [37]:
df_villes.population.sum()

np.int64(67648309)

In [40]:
df_villes.loc[
    # rows : 'WHERE'
    df_villes.population >= 500_000,
    # columns
    ['nom_standard', 'dep_code', 'population']
].sort_values('population', ascending=False)

      nom_standard dep_code  population
29244        Paris       75     2133111
4342     Marseille       13      873076
27082         Lyon       69      522250
11793     Toulouse       31      504078

In [ ]:
# - villes à 0 habitants
# - nom standard de la ville avec le plus d'habitants
# - population totale du 31
# - villes du 31 de plus de 50k habitants
# - Villes qui commencent par Tou
# - Villes qui contiennent ÿ
# - Villes qui n'ont pas de coordonnées du centre